site_name: Crawl4AI Documentation
site_description: 🔥🕷️ Crawl4AI, Open-source LLM Friendly Web Crawler & Scrapper
site_url: https://docs.crawl4ai.com
repo_url: https://github.com/unclecode/crawl4ai
repo_name: unclecode/crawl4ai
docs_dir: docs/md_v2

nav:
  - Home: 'index.md'
  - 'Installation': 'basic/installation.md'
  - 'Quick Start': 'basic/quickstart.md'
  
  - Basic:
    - 'Simple Crawling': 'basic/simple-crawling.md'
    - 'Output Formats': 'basic/output-formats.md'
    - 'Browser Configuration': 'basic/browser-config.md'
    - 'Page Interaction': 'basic/page-interaction.md'
    - 'Content Selection': 'basic/content-selection.md'

  - Advanced:
    - 'Content Processing': 'advanced/content-processing.md'
    - 'Magic Mode': 'advanced/magic-mode.md'
    - 'Hooks & Auth': 'advanced/hooks-auth.md'
    - 'Proxy & Security': 'advanced/proxy-security.md'
    - 'Session Management': 'advanced/session-management.md'
    - 'Session Management (Advanced)': 'advanced/session-management-advanced.md'
  
  - Extraction:
    - 'Overview': 'extraction/overview.md'
    - 'LLM Strategy': 'extraction/llm.md'
    - 'Json-CSS Extractor Basic': 'extraction/css.md'
    - 'Json-CSS Extractor Advanced': 'extraction/css-advanced.md'
    - 'Cosine Strategy': 'extraction/cosine.md'
    - 'Chunking': 'extraction/chunking.md'

  - API Reference:
    - 'AsyncWebCrawler': 'api/async-webcrawler.md'
    - 'AsyncWebCrawler.arun()': 'api/arun.md'
    - 'CrawlResult': 'api/crawl-result.md'
    - 'Strategies': 'api/strategies.md'


theme:
  name: terminal
  palette: dark

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - tables

extra_css:
  - assets/styles.css
  - assets/highlight.css
  - assets/dmvendor.css

extra_javascript:
  - assets/highlight.min.js
  - assets/highlight_init.js