# railway.toml
[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.memory]
soft = 2048 # 2GB min for Playwright
hard = 4096 # 4GB max

[deploy.scaling]
min = 1
max = 1
